[package]
name = "todo_web_api"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
axum = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1", features = ["full"] }
